# -*- mode: makefile -*-

######################################################################
# HAS Flags
######################################################################

# If defined to non-empty value, generates dynamic libraries.
# Do not forget to add -fPIC to CFLAGS and CFLAGS_DEBUG.

HAS_SHARED=0

######################################################################
# Directories
######################################################################

# mlcuddidl is installed with ocamlfind as the package "cudd"
# The installation directory is thus $(shell ocamlfind printconf destdir)/cudd
CAML_DIR = $(shell ocamlc -where)
CAMLIDL_DIR = $(shell ocamlfind query camlidl)

######################################################################
# Tools and Flags
######################################################################

# ocamlc compilation flags
OCAMLFLAGS = -annot
# ocamlopt compilation flags
OCAMLOPTFLAGS = -annot -inline 20

# C compiler
CC ?= gcc

# Other
LATEX=latex
DVIPS=dvips
DVIPDF=dvipdf
MAKEINDEX=makeindex

######################################################################
# Found by configure script
######################################################################

AR = /usr/bin/ar
RANLIB = /usr/bin/ranlib
SED = /usr/local/bin/gsed
M4 = /usr/bin/gm4
AWK = /usr/bin/awk
OCAMLC = /Users/sholtzen/.opam/4.09.0+flambda/bin/ocamlc.opt
OCAMLOPT = /Users/sholtzen/.opam/4.09.0+flambda/bin/ocamlopt.opt
OCAMLDEP = /Users/sholtzen/.opam/4.09.0+flambda/bin/ocamldep.opt
OCAMLDOC = /Users/sholtzen/.opam/4.09.0+flambda/bin/ocamldoc.opt
OCAMLMKLIB = /Users/sholtzen/.opam/4.09.0+flambda/bin/ocamlmklib.opt
OCAMLFIND = /Users/sholtzen/.opam/4.09.0+flambda/bin/ocamlfind
CAMLIDL = /Users/sholtzen/.opam/4.09.0+flambda/bin/camlidl
CC = /usr/bin/gcc
CXX = /usr/bin/g++
ENABLE_PROF = 
OCAMLPACK = ./ocamlpack
